export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOG_OUT = "LOG_OUT"; 
export const LOAD_PROFILE = "LOAD_PROFILE"; 


export const HOME_VIDEOS_SUCCESS = "HOME_VIEDOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIEDOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIEDOS_REQUEST";

export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIEDO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIEDO_FAIL";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIEDO_REQUEST";

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_VIDEO_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_VIDEO_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_VIDEO_FAIL";